name: Test TS build
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build_typescript:    
    runs-on: ubuntu-22.04
    steps:      
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install
        run: yarn install
      - name: check build typescript
        run: yarn build
